### ISSUE TITLE
Can not found minimap.py under neovim

### ISSUE THREAD

**Issue by Passw** [severin-lemaignan/vim-minimap#34]
It seems that could not find ```minimap.py``` file with ```neovim```
I am not sure whether this issue belong to ```neovim```

```
Error detected while processing function provider#python#Call:
line   18:
IOError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/neovim-0.0.38-py2.7.egg/neovim/msgpack_rpc/session.py", line 177, in handler
    rv = self._request_cb(name, args)
  File "/usr/local/lib/python2.7/dist-packages/neovim-0.0.38-py2.7.egg/neovim/api/common.py", line 237, in filter_request_cb
    walk(self._in, args, self, name, 'request'))
  File "/usr/local/lib/python2.7/dist-packages/neovim-0.0.38-py2.7.egg/neovim/plugin/host.py", line 65, in _on_request
    rv = handler(*args)
  File "/usr/local/share/nvim/runtime/autoload/provider/script_host.py", line 82, in python_execute_file
    with open(file_path) as f:
IOError: [Errno 2] No such file or directory: '/home/sun/.nvim/bundle/vim-minimap/autoload/minimap.py\n/home/sun/.vim/bundle/vim-minim
ap/autoload/minimap.py'
Error detected while processing function minimap#ShowMinimap..provider#python#Call:
line   18:
NameError("name 'showminimap' is not defined",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/neovim-0.0.38-py2.7.egg/neovim/msgpack_rpc/session.py", line 177, in handler
    rv = self._request_cb(name, args)
  File "/usr/local/lib/python2.7/dist-packages/neovim-0.0.38-py2.7.egg/neovim/api/common.py", line 237, in filter_request_cb
    walk(self._in, args, self, name, 'request'))
  File "/usr/local/lib/python2.7/dist-packages/neovim-0.0.38-py2.7.egg/neovim/plugin/host.py", line 65, in _on_request
    rv = handler(*args)
  File "/usr/local/share/nvim/runtime/autoload/provider/script_host.py", line 76, in python_execute
    exec(script, self.module.__dict__)
  File "<string>", line 1, in <module>
NameError: name 'showminimap' is not defined
```

**Comment by severin-lemaignan** [comment]
```
No such file or directory: '/home/sun/.nvim/bundle/vim-minimap/autoload/minimap.py\n/home/sun/.vim/bundle/vim-minimap/autoload/minimap.py'
```

This is indeed suspicious... I did not play much with neovim so far... If you can figure out if the issue is on vim-minimap side, I'd be happy to merge any required changes to make it work with neovim!

**Comment by severin-lemaignan** [comment]
Since it seems the issue is due to folder layout changes introduced by neovim, I'll mark it closed here. Please re-open if you think it should still be somehow handled by vim-minimap!
