### ISSUE TITLE
I'm getting the minimap desplayed, but also a bunch of errors ?!

### ISSUE THREAD

**Issue by Artem-Schander** [severin-lemaignan/vim-minimap#43]
My setup:

OSX
Neovim
Vundle
Python2 and 3 (both definitely accessible)

```
Fehler beim Ausführen von "function minimap#ShowMinimap[2]..provider#python#Call":
Zeile   18:
NvimError('Vim(return):NvimError("Vim(match):E867: (NFA) Unbekannter Operator \'\\\\%.\'",)',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 185, in handler
    rv = self._request_cb(name, args)
  File "/usr/local/lib/python2.7/site-packages/neovim/api/nvim.py", line 151, in filter_request_cb
    result = request_cb(self._from_nvim(name), args)
  File "/usr/local/lib/python2.7/site-packages/neovim/plugin/host.py", line 74, in _on_request
    rv = handler(*args)
  File "/usr/local/lib/python2.7/site-packages/neovim/plugin/script_host.py", line 75, in python_execute
    exec(script, self.module.__dict__)
  File "<string>", line 1, in <module>
NvimError: Vim(return):NvimError("Vim(match):E867: (NFA) Unbekannter Operator '\\%.'",)
Fehler beim Ausführen von "function minimap#ShowMinimap":
Zeile    2:
E171: Fehlendes :endif
```

if I try to navigate, I'm getting also errors

```
Fehler beim Ausführen von "function minimap#UpdateMinimap[2]..provider#python#Call":
Zeile   18:
    rv = self._request_cb(name, args)
```
```
Fehler beim Ausführen von "function minimap#UpdateMinimap[2]..provider#python#Call":
Zeile   18:
  File "/usr/local/lib/python2.7/site-packages/neovim/api/nvim.py", line 151, in filter_request_cb
```
```
Fehler beim Ausführen von "function minimap#UpdateMinimap[2]..provider#python#Call":
Zeile   18:
    result = request_cb(self._from_nvim(name), args)
```

...

Sorry about the german trace ^^

**Comment by Artem-Schander** [comment]
Sorry. I was prematurely.
It's a duplicate #42
