### ISSUE TITLE
Missing :endif on fresh install

### ISSUE THREAD

**Issue by agriffis** [severin-lemaignan/vim-minimap#71]
I just installed fresh 65ab020 on neovim nightly and I'm getting this error:

```
Error detected while processing function minimap#ToggleMinimap[2]..provider#python#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/aron/.vim/plugged/vim-minimap/autoload/minimap.py", line 67, in toggleminimap
    showminimap()
  File "/home/aron/.vim/plugged/vim-minimap/autoload/minimap.py", line 96, in showminimap
    vim.command(":call minimap#UpdateMinimap()")
  File "/usr/lib/python2.7/site-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/usr/lib/python2.7/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
NvimError: Vim(return):Traceback (most recent call last):
Error detected while processing function minimap#ToggleMinimap:
line    2:
E171: Missing :endif
```

**Comment by agriffis** [comment]
Clearly the `endif` is there in the code, so this seems to be something else going wrong

**Comment by perryao** [comment]
I'm running into the same issue. I'm not very fluent in vimscript or vim plugin development, but I tried commenting out a few lines of code in minimap.py to see if I could narrow down where the issue is coming from. 

If I comment out just [line 59](https://github.com/severin-lemaignan/vim-minimap/blob/master/autoload/minimap.py#L59), I no longer see an error and the minimap pane opens, just without any content. 

On that same line, if I just remove `* MinimapUpdate` so the full line is 

`vim.command(':autocmd CursorMoved,CursorMovedI,TextChanged,TextChangedI,BufWinEnter')`

vim prints out all the autocommands but still shows the empty minimap pane without error.

I'm not really sure if this is helpful or not, but wanted to share in case it helps someone else debug.
