### ISSUE TITLE
Error detected but minimap launches to some extent

### ISSUE THREAD

**Issue by NdranC** [severin-lemaignan/vim-minimap#79]
I'm in Arch and I installed both "nvim" and "phyton-pynvim" packages.

When I launch the minimap I get this error:

> Error detected while processing function minimap#ShowMinimap[4]..provider#python3#Call:
> line   18:
> Error invoking 'python_execute' on channel 3 (python3-script-host):
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/ndranc/.config/nvim/plugged/vim-minimap/autoload/minimap.py", line 96, in showminimap
>     vim.command(":call minimap#UpdateMinimap()")
>   File "/usr/lib/python3.8/site-packages/pynvim/api/nvim.py", line 287, in command
>     return self.request('nvim_command', string, **kwargs)
>   File "/usr/lib/python3.8/site-packages/pynvim/api/nvim.py", line 182, in request
>     res = self._session.request(name, *args, **kwargs)
>   File "/usr/lib/python3.8/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
>     raise self.error_wrapper(err)
> pynvim.api.common.NvimError: Vim(return):Error invoking 'python_execute' on channel 3 (python3-script-host):
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/ndranc/.config/nvim/plugged/vim-minimap/autoload/minimap.py", line 160, in updateminimap
>     vim.current.window = minimap
>   File "/usr/lib/python3.8/site-packages/pynvim/api/nvim.py", line 534, in window
>     return self._session.request('nvim_set_current_win', window)
>   File "/usr/lib/python3.8/site-packages/pynvim/api/nvim.py", line 182, in request
>     res = self._session.request(name, *args, **kwargs)
>   File "/usr/lib/python3.8/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
>     raise self.error_wrapper(err)
> pynvim.api.common.NvimError: Failed to switch to window 1001
> Press ENTER or type command to continue

The minimap proceeds to open but it looks like this:
![image](https://user-images.githubusercontent.com/27837113/80869625-8b076e80-8c6f-11ea-8261-0e8de5defa7f.png)

Not sure if that is the way it's supposed to look but maybe I have to change the font since it doesn't seem to match the content very well. The minimap seems to "function" but I'm unable to toggle it or close it getting the following error when I try:

> Error detected while processing function minimap#CloseMinimap[4]..provider#python3#Call:
> line   18:
> Error invoking 'python_execute' on channel 3 (python3-script-host):
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/ndranc/.config/nvim/plugged/vim-minimap/autoload/minimap.py", line 213, in closeminimap
>     vim.current.window = minimap
>   File "/usr/lib/python3.8/site-packages/pynvim/api/nvim.py", line 534, in window
>     return self._session.request('nvim_set_current_win', window)
>   File "/usr/lib/python3.8/site-packages/pynvim/api/nvim.py", line 182, in request
>     res = self._session.request(name, *args, **kwargs)
>   File "/usr/lib/python3.8/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
>     raise self.error_wrapper(err)
> pynvim.api.common.NvimError: Failed to switch to window 1001
> Press ENTER or type command to continue

EDIT: My :CheckHealth gives me this error:
![image](https://user-images.githubusercontent.com/27837113/80872385-95316900-8c7f-11ea-9b59-9748a6433fb4.png)
Not sure if it's relevant to the plugin but I have both python3 (3.8) and python2 (2.7) installed and under $PATH.

**Comment by hp4k1h5** [comment]
im getting the same result. seems to be related to or duplicate of #42 . i would try following the instructions given in `:help provider-python` for python2 first. but there doesnt seem to be resolution to the 42 issue

**Comment by bechampion** [comment]
i did something horrid to avoid the message of error when u start:
`sys.tracebacklimit = 0`
and wrap the functions inside toggle with try except pass
```def toggleminimap():
    minimap = getmmwindow()
    if minimap:
        try:
            closeminimap()
        except:
            pass
    else:
        try:
            showminimap()
        except:
            pass
```
forgive me
