### ISSUE TITLE
Not working in NeoVim v0.5.0-594

### ISSUE THREAD

**Issue by abdalazizrashid** [severin-lemaignan/vim-minimap#80]
Starting Minimap will cause this error:
```
Error detected while processing function minimap#ShowMinimap[4]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/aziz/.vim/plugged/vim-minimap/autoload/minimap.py", line 96, in showminimap
    vim.command(":call minimap#UpdateMinimap()")
  File "/home/aziz/.local/lib/python3.8/site-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/home/aziz/.local/lib/python3.8/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/aziz/.local/lib/python3.8/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Vim(return):Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/aziz/.vim/plugged/vim-minimap/autoload/minimap.py", line 160, in updateminimap
    vim.current.window = minimap
  File "/home/aziz/.local/lib/python3.8/site-packages/pynvim/api/nvim.py", line 534, in window
    return self._session.request('nvim_set_current_win', window)
  File "/home/aziz/.local/lib/python3.8/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/aziz/.local/lib/python3.8/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Failed to switch to window 1006
Press ENTER or type command to continue
```

**Comment by hrqmonteiro** [comment]
Same thing here.

No one is looking into it? The dev?

**Comment by pmorgan3** [comment]
Same thing here

**Comment by keithkeekw** [comment]
Yeap. Getting the same error as well.

**Comment by kevinkleine** [comment]
same

**Comment by nluetts** [comment]
same on Neovim 0.6.0. The minimap is drawn, though.
